[default]
extend-ignore-identifiers-re = [
    "Mmaped",
    "mmaped",
    "arange",
    "Nd",
    "nin",
    "cudaDevAttrMaxSharedMemoryPerBlockOptin",
    "_thw",
    "thr",
    "nd",
    "uneeded",
    "tese",
    "seperable",
    "Seperable",
    "setp",
    "cna",
]

[files]
extend-exclude = [
    "mistralrs-pyo3/pdoc/*",
    "examples/server/phi3_duckduckgo_mistral.rs.ipynb",
    "calibration_data/*",
    "mistralrs-web-chat/static*"
]