[files]
extend-exclude = [
    ".git/",
    "calibration_data/",
    "examples/server/phi3_duckduckgo_mistral.rs.ipynb",
    "mistralrs-web-chat/static/",
    "mistralrs-cli/static/",
    "CLAUDE.md",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "cudaDevAttrMaxSharedMemoryPerBlockOptin",
    '"tese"',
    "setp\\.ne\\.b32",
    # metal_kernels
    "out uneeded values",
    "copy_gg_dynamic_nd1",
    "copy_gg_dynamic_nd2",
    "copy_gg_dynamic_nd3",
    "copy_g_nd1",
    "copy_g_nd2",
    "copy_g_nd3",
    "copy_gg_nd1",
    "copy_gg_nd2",
    "copy_gg_nd3",
    "elem_to_loc_2_nd",
    "elem_to_loc_3_nd",
    "thr_reduce",
    "(?i)thw",
    "iy",
    "mxfp4_get_max_smem_optin",
    "alog",
    "ba",
]

[type.rust.extend-identifiers]
"arange" = "arange"
"arange_step" = "arange_step"
"cna" = "cna"
"from_mmaped_safetensors" = "from_mmaped_safetensors"
"MmapedSafetensors" = "MmapedSafetensors"
"nin_shortcut" = "nin_shortcut"
"EmbedNd" = "EmbedNd"
"gather_nd" = "gather_nd"
"i_thw" = "i_thw"
"cached_img_thw" = "cached_img_thw"
"cached_vid_thw" = "cached_vid_thw"
"video_grid_thw" = "video_grid_thw"
"image_grid_thw" = "image_grid_thw"
"grid_thw" = "grid_thw"
"vision_grid_thw" = "vision_grid_thw"
"video_grid_thw_accum" = "video_grid_thw_accum"
"image_grid_thw_accum" = "image_grid_thw_accum"
"image_thw" = "image_thw"
"video_thw" = "video_thw"
"depthwise_seperable_out_channel" = "depthwise_seperable_out_channel"
"default_depthwise_seperable_out_channel" = "default_depthwise_seperable_out_channel"
"DepthWiseSeperableConv1d" = "DepthWiseSeperableConv1d"
