[book]
title = "mistral.rs Documentation"
description = "Blazingly fast LLM inference engine"
authors = ["Eric Buehler"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/EricLBuehler/mistral.rs"
edit-url-template = "https://github.com/EricLBuehler/mistral.rs/edit/master/docs/{path}"
site-url = "/mistral.rs/"

[output.html.search]
enable = true
limit-results = 30

[output.html.fold]
enable = true
level = 1
