name: CI / cuda

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-cuda:
    name: CI / cuda (${{ matrix.name }})

    # For security, only run automatically for:
    # - PRs from the same repo (not forks)
    # - manual workflow dispatch
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.name }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    runs-on: [self-hosted, Linux, ARM64, gpu, cuda]

    strategy:
      matrix:
        include:
          - name: cuda
            features: cuda,nccl
          # - name: cuda+nccl
          #   features: cuda,nccl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential libssl-dev protobuf-compiler pkg-config

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: CUDA sanity
        run: |
          nvidia-smi || true
          nvcc --version || true

      - name: Clippy
        run: cargo clippy --features ${{ matrix.features }}

      - name: Test
        run: cargo test --features ${{ matrix.features }}
